version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.14.1

jobs:
  prepare:
    <<: *defaults

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .docz/dist

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint

  release:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: npx semantic-release

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - release:
          requires:
            - lint
            - build
